name: Mirror to NXCT-UCL

on:
  push:
    branches:
      - main  # or your default branch if different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Push to NXCT-UCL mirror repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git remote add mirror https://x-access-token:${{ secrets.MIRROR_PUSH_TOKEN }}@github.com/NXCT-UCL/offset-cone-beam-CT-reconstruction.git
          
          git push --mirror mirror
